services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: ecommerce-backend-prod
    container_name: ecommerce-backend-prod
    working_dir: /app
    ports:
      - "9997:9997"
    environment:
      - DB_FILE=/app/data/contactus.db
      - GIN_MODE=release
      - ADMIN_API_KEY=rapist-boy-aayush
    volumes:
      - backend-data:/app/data
    networks:
      - prodnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9997/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  sqlite-web:
    image: coleifer/sqlite-web
    container_name: sqlite-web
    environment:
      - SQLITE_WEB_PASSWORD=myStrongPassword
      - SQLITE_WEB_PORT=8080
    command: ["sqlite_web", "-H", "0.0.0.0", "-p", "8080", "-P", "/data/contactus.db"]
    ports:
      - "8080:8080"
    volumes:
      - backend-data:/data
    networks:
      - prodnet
    restart: unless-stopped

networks:
  prodnet:
    driver: bridge

volumes:
  backend-data:
